[project]
name = "wt32-mockup"
version = "0.1.0"
description = "Esqueleto Flask Hello World"
requires-python = ">=3.9"
readme = "README.md"
authors = [
  { name = "Your Name" }
]
dependencies = [
  "flask>=2.3.0"
]
